// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using StaffManagementWebAPI.Models;
using System;

#nullable disable

namespace StaffManagementWebAPI.Migrations
{
	[DbContext(typeof(AppDbContext))]
	partial class AppDbContextModelSnapshot : ModelSnapshot
	{
		protected override void BuildModel(ModelBuilder modelBuilder)
		{
#pragma warning disable 612, 618
			modelBuilder
				.HasAnnotation("ProductVersion", "6.0.28")
				.HasAnnotation("Relational:MaxIdentifierLength", 128);

			SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

			modelBuilder.Entity("StaffManagementWebAPI.Models.Staff", b =>
				{
					b.Property<string>("StaffId")
						.HasMaxLength(8)
						.HasColumnType("nvarchar(8)");

					b.Property<DateTime>("Birthday")
						.HasColumnType("datetime2");

					b.Property<string>("FullName")
						.IsRequired()
						.HasMaxLength(100)
						.HasColumnType("nvarchar(100)");

					b.Property<int>("Gender")
						.HasMaxLength(1)
						.HasColumnType("int");

					b.HasKey("StaffId");

					b.ToTable("Staff");
				});
#pragma warning restore 612, 618
		}
	}
}
